name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm install -g eslint nyc
    - run: npm run lint
    # - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    # - run: chmod +x ./cc-test-reporter
    # - run: ./cc-test-reporter before-build
    - run: npm run coverage
    # - run: ./cc-test-reporter format-coverage -t lcov coverage/lcov.info
    # - run: ./cc-test-reporter upload-coverage
      env:
        CI: true
        # CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
